USE ame;

-- 删除主键
ALTER TABLE stu MODIFY id INT NOT NULL;
ALTER TABLE stu DROP PRIMARY KEY;

-- 添加主键
ALTER TABLE stu ADD PRIMARY KEY(id);
ALTER TABLE stu MODIFY id INT NOT NULL AUTO_INCREMENT;

-- 复制一张表，该表是没有主键的
CREATE TABLE stu2 SELECT * FROM stu;

-- 添加主键
ALTER TABLE stu2 MODIFY id INT NOT NULL AUTO_INCREMENT,ADD PRIMARY KEY(id);

DROP TABLE IF EXISTS stu2;



